site_name: 2026 VCE Software Development - Iona College Geelong
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes

nav:
  - Home: index.md
  - Code Repo:
    - code-repo/index.md
    - FOR Loops:
      - Simple: code-repo/for-loops-simple.md
      - Advanced: code-repo/for-loops-advanced.md
    - WHILE Loops:
      - Simple: code-repo/while-loops-simple.md
      - Advanced: code-repo/while-loops-advanced.md
    - DO/WHILE Loops:
      - Simple: code-repo/do-while-loops-simple.md
      - Advanced: code-repo/do-while-loops-advanced.md
  - Unit 3 - AoS1 - Programming:
    - Coursework: unit-3-outcome-1/coursework/index.md
    - Overview: unit-3-outcome-1/overview.md
    - Key Knowledge: unit-3-outcome-1/key-knowledge.md
    - Key Skills: unit-3-outcome-1/key-skills.md
    - "1. Data Types and Data Structures":
      - unit-3-outcome-1/coursework/1-data-types-and-data-structures/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/1-data-types-and-data-structures/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/1-data-types-and-data-structures/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/1-data-types-and-data-structures/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/1-data-types-and-data-structures/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/1-data-types-and-data-structures/e-extras.md
    - "2. Solution Requirements":
      - unit-3-outcome-1/coursework/2-solution-requirements/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/2-solution-requirements/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/2-solution-requirements/b-test-your-knowledge.md
      - "c. Applied Task": unit-3-outcome-1/coursework/2-solution-requirements/c-applied-task.md
      - "d. Extras": unit-3-outcome-1/coursework/2-solution-requirements/d-extras.md
    - "3. Control Functions - Validation - Errors":
      - unit-3-outcome-1/coursework/3-control-functions-validation-errors/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/3-control-functions-validation-errors/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/3-control-functions-validation-errors/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/3-control-functions-validation-errors/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/3-control-functions-validation-errors/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/3-control-functions-validation-errors/e-extras.md
    - "4. Naming Conventions - Internal Documentation - Debugging and Testing":
      - unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/4-naming-conventions-documentation-debugging/e-extras.md
    - "5. Design Tools for Representing Modules":
      - unit-3-outcome-1/coursework/5-design-tools-representing-modules/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/5-design-tools-representing-modules/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/5-design-tools-representing-modules/b-test-your-knowledge.md
      - "c. Applied Task": unit-3-outcome-1/coursework/5-design-tools-representing-modules/c-applied-task.md
      - "d. Extras": unit-3-outcome-1/coursework/5-design-tools-representing-modules/d-extras.md
    - "6. Checking That Modules Function Correctly":
      - unit-3-outcome-1/coursework/6-checking-modules-function-correctly/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/6-checking-modules-function-correctly/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/6-checking-modules-function-correctly/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/6-checking-modules-function-correctly/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/6-checking-modules-function-correctly/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/6-checking-modules-function-correctly/e-extras.md
    - "7. Data Sources - TXT, CSV and XML":
      - unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/7-data-sources-txt-csv-xml/e-extras.md
    - "8. Searching and Sorting Algorithms":
      - unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/8-searching-and-sorting-algorithms/e-extras.md
    - "9. Variables, Functions, and Classes":
      - unit-3-outcome-1/coursework/9-variables-functions-classes/index.md
      - "a. What You Need To Know": unit-3-outcome-1/coursework/9-variables-functions-classes/a-what-you-need-to-know.md
      - "b. Test Your Knowledge": unit-3-outcome-1/coursework/9-variables-functions-classes/b-test-your-knowledge.md
      - "c. Practical Examples": unit-3-outcome-1/coursework/9-variables-functions-classes/c-practical-examples.md
      - "d. Applied Task": unit-3-outcome-1/coursework/9-variables-functions-classes/d-applied-task.md
      - "e. Extras": unit-3-outcome-1/coursework/9-variables-functions-classes/e-extras.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
